### PR TITLE
Fix delegate abbrs

### PR DESCRIPTION
**Pull request by mathiasbynens**
The two- or three-letter abbreviations used in meeting notes are supposed to be unique identifiers tied to a specific person. Also, any one person should pick an abbreviation and stick to it across meetings.

However, there’s plenty of cases where delegates accidentally violate these rules, resulting in confusion. I’ve found examples of people with multiple abbrs, people accidentally “stealing” other’s abbrs even when they’re both attending the same meeting (!).

I’m trying to correct this situation.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
The abbr “SSA” has been used by three different people 😅

**Comment by mathiasbynens** [comment]
With that, all collisions are removed, and each delegate has a single, unique ID. The final list is the following:

```
Aaron Davis (ADS)
Abhijith Chatra (AC)
Adam Klein (AK)
Adrian Hall (AHL)
Aki Braun (AKI)
Akrosh Gandhi (AGI)
Alan Schmitt (AS)
Alex Rattray (ARY)
Alex Russell (AR)
Alex Vincent (AVT)
Aliaksander Palpko (APO)
Allen Wirfs-Brock (AWB)
Amal Hussein (AHN)
Andreas Rossberg (ARB)
Andres Suarez (ASZ)
Andrew Burgese (ABE)
Andrew Burgess (ABS)
Andrew Paprocki (API)
Anna Henningsen (AH)
Anne van Kesteren (AVK)
Arnaud Le Hors (ALH)
Ashley Hauck (AEH)
Ashley Williams (AWS)
Augustus Yuan (AYN)
Avik Chaudhuri (AVC)
Ben Coe (BCE)
Ben Lichtman (BLN)
Ben Newman (BN)
Ben Smith (BS)
Ben Titzer (BTR)
Benjamin Georges (BGS)
Benoit Girard (BGD)
Bernd Mathiske (BM)
Bert Belder (BBR)
Bill Ticehurst (BTT)
Boris Zbarsky (BZ)
Brad Green (BG)
Brad Nelson (BNN)
Bradley Farias (BFS)
Brandon Benvie (BB)
Brendan Eich (BE)
Brian Terlson (BT)
Brian Warner (BWR)
Brittany Storoz (BSZ)
Caio Gondim (CGM)
Caio Lima (CLA)
Caridy Patiño (CP)
Chip Morningstar (CM)
Chris Anderson (CAN)
Chris Hyle (CHE)
Chris Needham (CNM)
Christoph Nakazawa (CNA)
Christopher Blappert (CBT)
Clark Sampson (CSN)
Claude Pache (CPE)
Conrad Watt (CWT)
Conrad Watts (CWS)
Corey Frang (CF)
Cristian Mattarei (CMI)
Dale Bustad (DBD)
Dan Abramov (DAV)
Dan Gohman (DGN)
Dan Stefan (DAS)
Daniel Clifford (DCD)
Daniel Ehrenberg (DE)
Daniel Rosenwasser (DRR)
Dave Herman (DH)
David Teller (DTL)
David Turissini (DTI)
Dean Tribble (DT)
Devin Rousso (DRO)
Diego Ferreiro Val (DFV)
Dmitry Lomov (DL)
Dmitry Soshnikov (DS)
Domenic Denicola (DD)
Doug Crockford (DC)
Dr. Felienne Hermans (FHS)
Dustin Savery (DSY)
Edd Yerburgh (EYH)
Edward Yang (EY)
Emily Huynh (EHH)
Eric Faust (EFT)
Eric Ferraiuolo (EF)
Eric Holk (EHK)
Eric Toth (ET)
Erica Pramer (EPR)
Erik Arvidsson (EA)
Fabio Rocha (FRA)
Felipe Balbontín (FBN)
Filip Pizlo (FP)
Forrest Norvell (FN)
Frank Yung-Fong Tang (FTG)
Franziska Hinkelmann (FHN)
Gabriel Isenberg (GI)
Gabriel McAdams (GMS)
Georg Neis (GN)
Godfrey Chan (GCN)
Gorkem Yakin (GY)
Guilherme Hermeto (GHO)
Gus Caplan (GCL)
Guy Bedford (GB)
Henry Zhu (HZU)
Ian Halliday (IH)
Igor Minar (IMR)
Ilias Tsangaris (IT)
Isaac Durazo (IDO)
Isabelle Valet-Harper (IVH)
István Sebestyén (IS)
Jack Steinberg (JBS)
Jacob Groundwater (JBG)
Jafar Husain (JH)
Jake Archibald (JAD)
Jakob Kummerow (JKW)
James Burke (JRB)
James Kyle (JK)
James M Snell (JSL)
Jamund Ferguson (JXF)
Jason Williams (JWS)
Jasvir Naga (JNA)
Jaswanth Sreeram (JS)
Jean-Francois Paradis (JFP)
Jeff Morrison (JM)
JF Bastien (JFB)
Joe Lencioni (JLI)
Joe Mordetsky (JMY)
Joe Sepi (JSI)
Joffrey Richten (JRN)
John Buchanan (JB)
John Hax (JHX)
John Lenz (JLZ)
John McCutchan (JMC)
John Neumann (JN)
John Pampuch (JP)
John-David Dalton (JDD)
Jonathan Dallas (JDS)
Jonathan Keslin (JKN)
Jonathan Sampson (JSN)
Jonathan Turner (JT)
Jordan Gensler (JGR)
Jordan Harband (JHD)
Jorge Lopez (JEL)
Jory Burson (JBN)
Jose David Rodrigues Veloso (JVO)
Joshua Peek (JPK)
Joyee Cheung (JCG)
Juan Dopazo (JDO)
Julien Gilli (JGI)
Justin Fagnani (JFI)
Justin Ridgewell (JRL)
Kat Z. Marchán (KZM)
Katie Broida (KBA)
Keith Cirkel (KCL)
Keith Miller (KM)
Kent C. Dodds (KCD)
Kevin Gibbons (KG)
Kevin Reid (KR)
Kevin Smith (KS)
Kevin Venkiteswaran (KVN)
Kirill Cherkoshin (KCN)
Kris Gray (KGY)
Kyle Verrier (KVR)
Lars Hansen (LHN)
Lee Byron (LB)
Leland Richardson (LM)
Leo Balter (LBR)
Limin Zhu (LZU)
Lin Clark (LCK)
Logan Smyth (LSH)
Louis Lafreniere (LL)
Luke Hoban (LH)
Lyza Gardner (LGR)
Maël Nison (MNN)
Maggie Pint (MPT)
Mariko Kosaka (MKA)
Mark Honenberg (MH)
Mark S. Miller (MM)
Masud Rahman (MRN)
Mathias Bynens (MB)
Matt Johnson (MAJ)
Matt Miller (MMR)
Matt Sweeney (MS)
Mattijs Hoitink (MHK)
Maxim Aleksa (MAA)
Michael Ficarra (MF)
Michael Fig (MFG)
Michael Hablich (MHH)
Michael Saboff (MLS)
Michael Z Goddard (MZG)
Michal Hollman (MHN)
Mike Murry (MMY)
Mike Pennisi (MP)
Mike Samuel (MSL)
Mikeal Rogers (MRS)
Miško Hevery (MHY)
Mohamed Hegazy (MDH)
Morgan Phillips (MPS)
Mrelita Tiwari (MTI)
Mu-an Chiou (MCU)
Myles Borins (MBS)
Nagy Hostafa (NH)
Natalie Silvanovich (NSH)
Nathan Hammond (NHD)
Nebojša Ćirić (NC)
Nicolò Ribaudo (NRO)
Niko Matsakis (NM)
Nikolaus Papaspyrou (NPU)
Noah Tye (NTE)
Norbert Lindenberg (NL)
Oliver Hunt (OH)
Paolo Severini (PSI)
Patrick Soquet (PST)
Paul Leather (PLR)
Paul Leathers (PL)
Pedram Emrouznejad (PED)
Peter Hoddie (PHE)
Peter Jensen (PJ)
Peter van der Zee (PZE)
Philipp Dunkel (PDL)
Philippa Gardner (PGR)
Philippe Le Hégaret (PLH)
Pierre-Marie Dartus (PMD)
Pieter Ouwerkerk (POK)
Qiuyi Zhang (QZG)
Rafael Xavier (RX)
Rafeal Weinstein (RWN)
Randy Luecke (RLE)
Ravi Jayaramappan (RJN)
Rebecca Turner (RTR)
Reefath Rajali (RRI)
Reid Burke (RB)
Rex Jaeschke (RJE)
Richard Gibson (RGN)
Rick Hudson (RH)
Rick Markins (RMS)
Rick Waldron (RW)
Rob Palmer (RPR)
Robert Pamely (RPY)
Robin Morisset (RMT)
Robin Ricard (RRD)
Ron Buckton (RBN)
Ross Kirsling (RKG)
Saam Barati (SBI)
Sam Goto (SGO)
Sam Mussell (SML)
Sam Tobin-Hochstadt (STH)
Sanket Joshi (SJI)
Sarah D'Onofrio (SDO)
Sathya Gunasekasan (SGN)
Satish Chondra (SC)
Scott Myers (SMS)
Sean Larkin (SLN)
Sebastian Markbåge (SM)
Sebastian McKenzie (SMK)
Seo-Young Hwang (SYH)
Sergey Rubanov (SRV)
Seth Brenith (SBH)
Shaheer Shabbir (SSR)
Shane Carr (SCR)
Shane Carr (SFC)
Shelby Hubick (SHK)
Shelley Vohr (SVR)
Shu-yu Guo (SYG)
Simon Kaegi (SK)
Sri Pillalamarri (SPI)
Staś Małolepszy (STM)
Stefan Penner (SP)
Stephen Murphy (SMY)
Steve Faulkner (SFR)
Steven Loomis (SLS)
Sung-Jae Lee (SJL)
Suraj Sharma (SUS)
Surma (SUR)
Sven Sauleau (SSA)
Szabolcs Szabolcsi-Toth (SZT)
Tab Atkins (TAB)
Tadeu Zagallo (TZO)
Tatiana Shpeisman (TS)
Taylor Woll (TW)
Theresa O'Connor (TOC)
Thomas Levy (TLY)
Thomas Nattestad (TND)
Thomas Wood (TWD)
Tierney Cyren (TCN)
Till Schneidereit (TST)
Tim Disney (TD)
Tim McClure (TME)
Timothy Gu (TGU)
Tom Care (TC)
Tom Dale (TDE)
Tom Van-Cutsem (TVC)
Toon Verwaest (TVT)
Trevor Bliss (TBS)
Tyler Kellen (TKN)
Tzvetan Mikov (TMV)
Valerie Young (VYG)
Vladan Djeric (VDC)
Vladimir Matveev (VM)
Waldemar Horwat (WH)
Yang Guo (YGO)
Yehuda Katz (YK)
Yulia Startsev (YSV)
Zibi Braniecki (ZB)
```

It’d be great to add this as a file to the reflector, so that we can link to it in draft meeting note docs. Something like: `Use your [existing abbreviations](link)! If you don’t already have an abbreviation, choose any three-letter combination that is not [already in use](link to same file), and send a PR to add it upstream.`

**Comment by hax** [comment]
@mathiasbynens Could you change my name from "John Hax (JHX)" to my real name?

My real name is <ruby>贺<rt>He</rt>师<rt>Shi</rt>俊<rt>Jun</rt></ruby> , in most places I use "HE Shi-Jun" as spelling, but I'm fine with "Shi-jun He" if we have a convention that always put family name in the last. 

I'm ok with any abbr, HE or SHE or SH or SJH though i would be prefer HAX if it not violate our abbr rule.

Thank you!

BTW, `Qiuyi Zhang (QZG)` and `Joyee Cheung (JCG)` is same person (with two spelling convention). @joyeecheung ?

**Comment by joyeecheung** [comment]
@hax thanks for the ping, I'd prefer JCG as I tend to introduce myself as Joyee at the meetings so this is probably easier for note takers to recognize. (that and also Qiuyi is not easy to pronounce in English).

**Comment by mathiasbynens** [comment]
@hax and @joyeecheung Of course! Happy to make those changes. (I had compiled that list by looking at all meeting notes in this repo.) Will make the changes now.

**Comment by mathiasbynens** [comment]
@hax @joyeecheung Made the changes to the list above and to the PR. But please note that it’s your responsibility to use your correct/preferred name in the meeting notes documents.

**Comment by sffc** [comment]
Email exchange with Michael Saboff:

> Hi Michael,
> 
> For the notes for TC39, we were inconsistent in our usage of "MS" versus "MLS" for your name.  In previous meetings you were labeled as "MS", but this meeting "MLS" became more common.  Which one is your preference?
> 
> Shane

-----

> Shane,
> 
> First of all, thanks for your note taking.  I made the change to MLS, but let’s make it MS since that is what I used at prior meetings.  I can make the change if you like in the three docs.
> 
> - Michael

**Comment by mathiasbynens** [comment]
@sffc @msaboff MS was already taken by Matt Sweeney, which is why this PR standardizes on the next abbr @msaboff used.

**Comment by chicoxyzzy** [comment]
Perhaps `participants.txt` is a better file name since not all people from the list are delegates.

**Comment by sffc** [comment]
Thanks by the way for compiling this list.  This will help with note-taking in the future.

Should we also use this list for ECMA-402 and add ECMA-402 delegates who aren't TC39 delegates to the same list?

**Comment by ljharb** [comment]
It seems like it'd make sense, since non-262 402 folks will likely occasionally participate in 262 meetings.

**Pull request merged**
