### PR TITLE
Add meeting notes for 2016-05

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by leobalter** [comment]
Merging to master myself as it only add new files.

**Comment by zloirock** [comment]
@leobalter addition those notes to `es7/` path looks strange.

**Comment by leobalter** [comment]
@zloirock agreed, but I'm trying to follow the same as in last year, where it used es7 folder after es6 got published.

I believe the best here is to reorganize folders by year in another PR.

**Comment by ljharb** [comment]
I don't think we should "reorganize" the folders - but it makes sense for the July meeting to start in an "es2017" folder.

**Comment by rauschma** [comment]
For the long run, organization by year makes a lot of sense to me, especially since meetings sometimes look forward and/or backward, too.

**Comment by azu** [comment]
Um, `es7/2016-05/` directiory is missing in [master branch](https://github.com/rwaldron/tc39-notes/tree/master/es7)... Where is?

**Comment by ljharb** [comment]
@azu it's been temporarily reverted so committee members have enough time to review the notes.

**Comment by azu** [comment]
@ljharb OK. Thanks for quick response.

**Pull request merged**
